sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t ganesh/docker-react1 -f Dockerfile.dev .

script:
  - docker run -e CI=true ganesh/docker-react1 npm run test


